### ISSUE TITLE
In the section 'Create a data migration task' (#create-a-data-migration-task), `target-database:` is not indented.

### ISSUE THREAD

**Issue by BarDev** [pingcap/docs-dm#676]
File: [/en/get-started.md](https://docs.pingcap.com/tidb-data-migration/v1.0/get-started)

Currently, it's this. 
Notice
* `target-database:` children need to be indented
* ` do-dbs: ["testdm"]` needs to be indented 

```
---
name: testdm
task-mode: all
target-database:
host: "127.0.0.1"
port: 4000
user: "root"
password: "" # If the password is not null, it is recommended to use password encrypted with dmctl.
mysql-instances:
  - source-id: "mysql-replica-01"
    block-allow-list:  "ba-rule1"
block-allow-list:
ba-rule1:
    do-dbs: ["testdm"]
```

Should be

```
---
name: testdm
task-mode: all
target-database:
    host: "127.0.0.1"
    port: 4000
    user: "root"
    password: "" # If the password is not null, it is recommended to use password encrypted with dmctl.
mysql-instances:
  - source-id: "mysql-replica-01"
    block-allow-list:  "ba-rule1"
block-allow-list:
    ba-rule1:
        do-dbs: ["testdm"]
```
